### PR TITLE
main.cpp / protocol.h update seeders and ports

### PR DESCRIPTION
**Pull request by j50ng**
Added the correct active mainnet and testnet seeders to main.cpp and modified protocol.h to add the correct testnet port.

### CODE REVIEW

**Review by ycagel — APPROVED** [review]
Thanks for the efforts John! 

aCK

**Review by fgabelmannjr — APPROVED** [review]
ACK, great work John!

**Comment by JaredTate** [comment]
Thanks for doing this and helping get the seeds updated. And thanks to everyone helping to run new seeders and get testnet back up. Here are a few more thoughts about seeders:

We need to also add new seeders to https://github.com/DigiByte-Core/digibyte/tree/feature/8.22.0,  although it doesn't hurt to have it in the seeder master as well as the current DigiByte core master too if people want to compile seeders or the core client themselves with updated seeders. In my opinion, it doesn't make sense to release a new version of DGB core just for this though since when we are close to an 8.22 release.

2nd, it's not a good idea to add static IPS for many reasons as a core seeder.  1st, it makes that server IP an easy target to launch an attack on the seeder server which allows an attacker to launch several other kinds of attacks on the DGB blockchain. 2nd, many hosts use dynamic IP's that change from time to time unless you pay for a fixed IP, 3rd you lose the ability to change hosts or servers as it requires releasing an entirely new version of DGB core to update seeds as well as other seeders to update. Much better to use DNS names that are flexible, more protected, and easier to work with.

3rd, why are you adding 127.0.0.1? That's a loop to localhost and makes no sense as a seeder as it doesn't do anything but timeout the client.

See Bitcoin main seeder for reference: https://github.com/sipa/bitcoin-seeder/blob/master/main.cpp#L421

**Comment by j50ng** [comment]
The IP addresses added to testnet seeders are testnet nodes that were recently deployed by community members.  These IPs were initially put there to bootstrap the testnet seeder environment as there were none that were functioning.  Once there are enough seeders, the thought was to then request to remove those static IPs in parallel with others submitting PRs to review and approve/add their seeder hosts. 

The 127.0.0.1 loopback/localhost host was added so that the seeder could connect to your local node if you were running one on the same VPS.  I agree, in retrospect, that should probably be removed as a default and the README could add that as an optional instruction for those that are planning to run the seeder on the same VPS as their node, considering a local node is not needed for running the seeder.

@saltedlolly - perhaps you can modify the README to give the option for those who are planning to run the seeder on the same VPS as their node to include their localhost 127.0.0.1 to main.cpp before compiling.

**Comment by saltedlolly** [comment]
Given how lightweight the DNS Seeder software is, and that it rarely needs to be restarted, my assumption has been that, if there is no local node, then the loopback IP address will simply timeout the first time it is run, and not keep continuously looking for it. The seeder software would presumably ban the local IP once it establishes that there is no node there. That said, I am not familiar with the inner workings of the DNS seeder, and if it does repeatedly keep polling the localhost, then I agree, and lets remove the 127.0.0.1 IP address. It was mainly added to make it as easy as possible to setup the DNS seeder, since it can automatically connect to a local node out-the-box without requiring any manual edits. 

I can update the instructions explaining how to add the loopback IP if you have a local node on the VPS.

**Comment by saltedlolly** [comment]
I have been updating the list of new seeders [here](https://1drv.ms/w/s!AsTGLNLt5YBypgadXSi16NEPaXes).

(The original list for v7.17.3 is [here](https://1drv.ms/w/s!AsTGLNLt5YBypgS8ljrD5-aSSqol).)

Once we get enough new seeders for testnet and mainnet, and everyone agrees, I do think it would be good to put out a v7.17.4 release simply to get these fixes out there now, so we no longer have to worry about this issue. 

Currently there are only two working mainnet seeders and no working testnet seeders in 7.17.3, making the network pretty vulnerable, and it is pretty difficult for people to connect to and use the testnet network right now, due also to the testnet difficulty bug that Jonathan has identified.

Correct me if I am wrong, but there are still several obstacles to overcome in v8, with or without new algos, and a release could potentially still be several months away, no? The new seeders and hopefully a fix to that testnet bug could be rolled out in a matter of weeks.

To prepare for a potential v7.17.4  release, we presumably require a v7.17.4 dev branch for DigiByte Core that we can make PRs to. Can any Core devs advise on the best approach for doing this?

**Pull request merged**
