### PR TITLE
Improve README file

### PR DESCRIPTION
**Pull request by saltedlolly**

### CODE REVIEW

**Comment by saltedlolly** [comment]
Note: Nothing has been removed from the original README file. I have simply reorganised, and added missing information.

**Comment by saltedlolly** [comment]
You can read this new README.md file here: https://github.com/saltedlolly/digibyte-seeder/tree/dev

**Review by ycagel — APPROVED** [review]
Great edits Olly! Thanks for taking the initiative on this.

aCK

**Review by gto90 — APPROVED** [review]
ACK!  Thanks for updating this documentation!

**Pull request merged**
