### PR TITLE
Add testnet config option to startseeder.sh

### PR DESCRIPTION
**Pull request by saltedlolly**
Also, clean up readme.

### CODE REVIEW

**Review by gto90 — APPROVED** [review]
ACK

**Review by JaredTate — APPROVED** [review]
cACK. Thanks for working on this!

**Comment by j50ng** [comment]
image

Currently, seed.digibyte.help does not resolve.

image

**Review by j50ng — APPROVED** [review]
cACK

**Review by ycagel — APPROVED** [review]
cACK

**Pull request merged**
