### PR TITLE
Update testnet minimal block height.

### PR DESCRIPTION
**Pull request by ghost**
**Update Testnet minimal block height.** And update Mainnet minimal block height. 
Testnet nodes with blocks under 2755000 will not longer being seeded by the testnet seed servers.

digibyte.link                **2754930 Testnet nodes.**
digibyte.help              Good nodes.
digibyteblockchain.org    **2754930 Testnet nodes** && good nodes.
digibyte.services        **2754930 Testnet nodes** && good nodes.
digibyteseed.com              Good nodes.

Servers will stop seeding till block height 2755000 is reached. This is around 3/4 march 2024. 

Screenshot from 2024-02-05 17-53-47

### CODE REVIEW

**Review by JaredTate — APPROVED** [review]
cACK. Cheers

**Review by ycagel — APPROVED** [review]
cACK. Thanks @Jongjan88!

**Review by saltedlolly — APPROVED** [review]
ACK. Many thanks. This successfully bans nodes on the bad testnet chain.

**Review by gto90 — APPROVED** [review]
utACK

**Pull request merged**
