### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by cdonnachie**
Add New DNS seeders for Mainnet and Testnet
- seed.digibyte.services
- testnetseed.digibyte.services

### CODE REVIEW

**Review by saltedlolly — APPROVED** [review]
utACK

Looks good.

**Review by gto90 — DISMISSED** [review]
utACK

**Review by j50ng — APPROVED** [review]
utACK

**Comment by saltedlolly** [comment]
Concept ACK

Not being a C++ developer I am not comfortable signing off on this. That said, I have read through the changes, and am reasonably confident that I understand them. They look good to me. I am also running this new version and it appears to work as intended. (Not a negative reflection on you @cdonnachie, simply an acknowledgement of my lack of C++ skills!)

**Review by gto90 — APPROVED** [review]
utACK

**Review by j50ng — APPROVED** [review]
utACK

**Review by ycagel — APPROVED** [review]
cACK

**Pull request merged**
