### PR TITLE
Add-Seeder

### PR DESCRIPTION
**Pull request by Quakeitup**
Added seed.quakeguy.com

### CODE REVIEW

**Review by saltedlolly — APPROVED** [review]
tACK. Many thanks.

https://www.whatsmydns.net/#A/seed.quakeguy.com

**Review by ycagel — APPROVED** [review]
tACK. Appreciate all your efforts!

**Review by JaredTate — APPROVED** [review]
ACK. Thanks for adding your seed.

**Review by Sbosvk — APPROVED** [review]
tACK. Good to be merged.

**Pull request merged**
