### PR TITLE
Update db.h

### PR DESCRIPTION
**Pull request by ghost**
Minimum required node block height.

2023-12-06 11:14 UTC
Testnet: 2690567
Mainnet: 18349664

### CODE REVIEW

**Review by saltedlolly — APPROVED** [review]
This ensures that nodes must have reached a minimum block height before they are accepted by the DigiByte Seeder and can be provided to other nodes to connect to.

New testnet minimum: 2690000
New mainnet minimum: 18340000

Currently the testnet seeder in particular is able to serve nodes with zero blocks.

This fix makes sense to me.

cACK

**Comment by saltedlolly** [comment]
This explains: https://youtu.be/DsaxbwwVEXk?t=288

**Review by gto90 — APPROVED** [review]
cACK

**Review by j50ng — APPROVED** [review]
cACK

This does make sense to not have clients connecting to a node that hasn't sufficiently synched and ultimately would reduce attempts to connect to useless nodes.  I have not tested this, but it's worth making sure this is tested.  As the blockchain grows and reaches higher block heights, this minimum block height should be periodically updated (increased).  

Makes sense @Jongjan88!

**Review by ycagel — APPROVED** [review]
cACK. Agree with @j50ng that appropriate testing needs to be done. Thanks @Jongjan88!

**Pull request merged**
